version: '3'
services:
  redis:
    image: "redis:latest"
    container_name: "redis_server"
    ports:
      - "6379:6379"

  PACO:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "PACO"
    ports:
      - "8050:8050"
    depends_on:
      - redis
    command: ["./python3 src/app.py"]
