name: Release

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/paco:${{ github.ref_name }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/paco:${{ github.ref_name }}

    - name: Update release with Docker image link
      run: |
        release_id=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }} | jq -r .id)
        docker_image_url="https://hub.docker.com/r/${{ secrets.DOCKER_USERNAME }}/paco/tags?page=1&name=${{ github.ref_name }}"
        curl -s \
          -X PATCH \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"body\": \"Docker image available at [Docker Hub](${docker_image_url})\"}" \
          https://api.github.com/repos/${{ github.repository }}/releases/${release_id}
