name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Export PYTHONPATH and print its value
      run: |
        export PYTHONPATH="${{ github.workspace }}/PACO/tests"
        echo "PYTHONPATH is set to: $PYTHONPATH"

    - name: Run tests
      run: |
        export PYTHONPATH="${{ github.workspace }}/PACO/tests"
        python -m unittest discover -s tests
