name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}/tests:${{ github.workspace }}/src
      run: |
        python -m saturate_execution/test_saturate_execution.py
        python -m searcher/test_found_strategy.py
